// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod chess {
    pub mod types {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Piece types
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum PieceType {
                Pawn,
                Knight,
                Bishop,
                Rook,
                Queen,
                King,
            }
            impl ::core::fmt::Debug for PieceType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PieceType::Pawn => f.debug_tuple("PieceType::Pawn").finish(),
                        PieceType::Knight => f.debug_tuple("PieceType::Knight").finish(),
                        PieceType::Bishop => f.debug_tuple("PieceType::Bishop").finish(),
                        PieceType::Rook => f.debug_tuple("PieceType::Rook").finish(),
                        PieceType::Queen => f.debug_tuple("PieceType::Queen").finish(),
                        PieceType::King => f.debug_tuple("PieceType::King").finish(),
                    }
                }
            }
            impl PieceType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> PieceType {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => PieceType::Pawn,
                        1 => PieceType::Knight,
                        2 => PieceType::Bishop,
                        3 => PieceType::Rook,
                        4 => PieceType::Queen,
                        5 => PieceType::King,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Colors
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Color {
                White,
                Black,
            }
            impl ::core::fmt::Debug for Color {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Color::White => f.debug_tuple("Color::White").finish(),
                        Color::Black => f.debug_tuple("Color::Black").finish(),
                    }
                }
            }
            impl Color {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Color {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Color::White,
                        1 => Color::Black,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// A piece on the board
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Piece {
                pub piece_type: PieceType,
                pub color: Color,
            }
            impl ::core::fmt::Debug for Piece {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Piece")
                        .field("piece-type", &self.piece_type)
                        .field("color", &self.color)
                        .finish()
                }
            }
            /// Square on the board (0-63, where 0=a1, 63=h8)
            pub type Square = u8;
            /// A move in UCI format (e.g., "e2e4", "e7e8q" for promotion)
            pub type Move = _rt::String;
            /// A single entry in the move history
            #[derive(Clone)]
            pub struct MoveHistoryEntry {
                pub uci_move: Move,
                pub resulting_fen: _rt::String,
            }
            impl ::core::fmt::Debug for MoveHistoryEntry {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("MoveHistoryEntry")
                        .field("uci-move", &self.uci_move)
                        .field("resulting-fen", &self.resulting_fen)
                        .finish()
                }
            }
            /// Castling rights
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Castling {
                pub white_kingside: bool,
                pub white_queenside: bool,
                pub black_kingside: bool,
                pub black_queenside: bool,
            }
            impl ::core::fmt::Debug for Castling {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Castling")
                        .field("white-kingside", &self.white_kingside)
                        .field("white-queenside", &self.white_queenside)
                        .field("black-kingside", &self.black_kingside)
                        .field("black-queenside", &self.black_queenside)
                        .finish()
                }
            }
            /// Board representation - array of 64 squares
            /// Each square is either empty (none) or has a piece
            #[derive(Clone)]
            pub struct BoardState {
                pub squares: _rt::Vec<Option<Piece>>,
                pub turn: Color,
                pub castling_rights: Castling,
                pub en_passant: Option<Square>,
                pub halfmove_clock: u16,
                pub fullmove_number: u16,
                pub move_history: _rt::Vec<MoveHistoryEntry>,
            }
            impl ::core::fmt::Debug for BoardState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("BoardState")
                        .field("squares", &self.squares)
                        .field("turn", &self.turn)
                        .field("castling-rights", &self.castling_rights)
                        .field("en-passant", &self.en_passant)
                        .field("halfmove-clock", &self.halfmove_clock)
                        .field("fullmove-number", &self.fullmove_number)
                        .field("move-history", &self.move_history)
                        .finish()
                }
            }
            /// Game result
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum GameResult {
                InProgress,
                Checkmate,
                Stalemate,
                Draw,
            }
            impl ::core::fmt::Debug for GameResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        GameResult::InProgress => {
                            f.debug_tuple("GameResult::InProgress").finish()
                        }
                        GameResult::Checkmate => {
                            f.debug_tuple("GameResult::Checkmate").finish()
                        }
                        GameResult::Stalemate => {
                            f.debug_tuple("GameResult::Stalemate").finish()
                        }
                        GameResult::Draw => f.debug_tuple("GameResult::Draw").finish(),
                    }
                }
            }
            impl GameResult {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> GameResult {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => GameResult::InProgress,
                        1 => GameResult::Checkmate,
                        2 => GameResult::Stalemate,
                        3 => GameResult::Draw,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Engine error types
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum EngineError {
                InvalidFen,
                IllegalMove,
                GameOver,
            }
            impl EngineError {
                pub fn name(&self) -> &'static str {
                    match self {
                        EngineError::InvalidFen => "invalid-fen",
                        EngineError::IllegalMove => "illegal-move",
                        EngineError::GameOver => "game-over",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        EngineError::InvalidFen => "",
                        EngineError::IllegalMove => "",
                        EngineError::GameOver => "",
                    }
                }
            }
            impl ::core::fmt::Debug for EngineError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("EngineError")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for EngineError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), * self as i32)
                }
            }
            impl std::error::Error for EngineError {}
            impl EngineError {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> EngineError {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => EngineError::InvalidFen,
                        1 => EngineError::IllegalMove,
                        2 => EngineError::GameOver,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod chess {
        pub mod engine {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod engine {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type BoardState = super::super::super::super::chess::types::types::BoardState;
                pub type Move = super::super::super::super::chess::types::types::Move;
                pub type GameResult = super::super::super::super::chess::types::types::GameResult;
                pub type Color = super::super::super::super::chess::types::types::Color;
                pub type Piece = super::super::super::super::chess::types::types::Piece;
                pub type Square = super::super::super::super::chess::types::types::Square;
                pub type EngineError = super::super::super::super::chess::types::types::EngineError;
                pub type MoveHistoryEntry = super::super::super::super::chess::types::types::MoveHistoryEntry;
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Game {
                    handle: _rt::Resource<Game>,
                }
                type _GameRep<T> = Option<T>;
                impl Game {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Game`.
                    pub fn new<T: GuestGame>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _GameRep<T> = Some(val);
                        let ptr: *mut _GameRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestGame>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestGame>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestGame>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _GameRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestGame>(&self) -> *mut _GameRep<T> {
                        Game::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Game`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct GameBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Game>,
                }
                impl<'a> GameBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestGame>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _GameRep<T> {
                        Game::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Game {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]chess:engine/engine@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]game"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_game_cabi<T: GuestGame>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = Game::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_static_game_from_fen_cabi<T: GuestGame>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::from_fen(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr2.add(4).cast::<i32>() = (e).take_handle() as i32;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            *ptr2.add(4).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_fen_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_fen(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_get_fen<T: GuestGame>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_board_state_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_board_state(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::chess::types::types::BoardState {
                        squares: squares2,
                        turn: turn2,
                        castling_rights: castling_rights2,
                        en_passant: en_passant2,
                        halfmove_clock: halfmove_clock2,
                        fullmove_number: fullmove_number2,
                        move_history: move_history2,
                    } = result0;
                    let vec4 = squares2;
                    let len4 = vec4.len();
                    let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec4.len() * 3,
                        1,
                    );
                    let result4 = if layout4.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout4);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec4.into_iter().enumerate() {
                        let base = result4.add(i * 3);
                        {
                            match e {
                                Some(e) => {
                                    *base.add(0).cast::<u8>() = (1i32) as u8;
                                    let super::super::super::super::chess::types::types::Piece {
                                        piece_type: piece_type3,
                                        color: color3,
                                    } = e;
                                    *base.add(1).cast::<u8>() = (piece_type3.clone() as i32)
                                        as u8;
                                    *base.add(2).cast::<u8>() = (color3.clone() as i32) as u8;
                                }
                                None => {
                                    *base.add(0).cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1.add(0).cast::<*mut u8>() = result4;
                    *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (turn2
                        .clone() as i32) as u8;
                    let super::super::super::super::chess::types::types::Castling {
                        white_kingside: white_kingside5,
                        white_queenside: white_queenside5,
                        black_kingside: black_kingside5,
                        black_queenside: black_queenside5,
                    } = castling_rights2;
                    *ptr1
                        .add(1 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match white_kingside5 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(2 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match white_queenside5 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(3 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match black_kingside5 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match black_queenside5 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    match en_passant2 {
                        Some(e) => {
                            *ptr1
                                .add(5 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            *ptr1
                                .add(6 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(e)) as u8;
                        }
                        None => {
                            *ptr1
                                .add(5 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    *ptr1
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u16>() = (_rt::as_i32(halfmove_clock2)) as u16;
                    *ptr1
                        .add(10 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u16>() = (_rt::as_i32(fullmove_number2)) as u16;
                    let vec9 = move_history2;
                    let len9 = vec9.len();
                    let layout9 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec9.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result9 = if layout9.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout9).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout9);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec9.into_iter().enumerate() {
                        let base = result9
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::chess::types::types::MoveHistoryEntry {
                                uci_move: uci_move6,
                                resulting_fen: resulting_fen6,
                            } = e;
                            let vec7 = (uci_move6.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *base.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                            let vec8 = (resulting_fen6.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                    }
                    *ptr1
                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len9;
                    *ptr1
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result9;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_get_board_state<T: GuestGame>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 3, 1);
                    let l3 = *arg0
                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *arg0
                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base9 = l3;
                    let len9 = l4;
                    for i in 0..len9 {
                        let base = base9
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l5 = *base.add(0).cast::<*mut u8>();
                            let l6 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                            let l7 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l7, l8, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base9,
                        len9 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_legal_moves_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_legal_moves(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = result0;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = result3;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_get_legal_moves<T: GuestGame>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_make_move_cabi<T: GuestGame>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::make_move(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            *ptr2.add(1).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_game_result_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_game_result(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_is_check_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::is_check(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_turn_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_turn(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_piece_at_cabi<T: GuestGame>(
                    arg0: *mut u8,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_piece_at(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                        arg1 as u8,
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Some(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::chess::types::types::Piece {
                                piece_type: piece_type2,
                                color: color2,
                            } = e;
                            *ptr1.add(1).cast::<u8>() = (piece_type2.clone() as i32)
                                as u8;
                            *ptr1.add(2).cast::<u8>() = (color2.clone() as i32) as u8;
                        }
                        None => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_get_move_history_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_move_history(
                        unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::chess::types::types::MoveHistoryEntry {
                                uci_move: uci_move2,
                                resulting_fen: resulting_fen2,
                            } = e;
                            let vec3 = (uci_move2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (resulting_fen2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1.add(0).cast::<*mut u8>() = result5;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_game_get_move_history<T: GuestGame>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base6 = l0;
                    let len6 = l1;
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_game_reset_cabi<T: GuestGame>(
                    arg0: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::reset(unsafe { GameBorrow::lift(arg0 as u32 as usize) }.get());
                }
                pub trait Guest {
                    type Game: GuestGame;
                }
                pub trait GuestGame: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]chess:engine/engine@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]game"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]chess:engine/engine@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]game"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new() -> Self;
                    fn from_fen(fen: _rt::String) -> Result<Game, EngineError>;
                    fn get_fen(&self) -> _rt::String;
                    fn get_board_state(&self) -> BoardState;
                    fn get_legal_moves(&self) -> _rt::Vec<Move>;
                    fn make_move(&self, uci: Move) -> Result<(), EngineError>;
                    fn get_game_result(&self) -> GameResult;
                    fn is_check(&self) -> bool;
                    fn get_turn(&self) -> Color;
                    fn get_piece_at(&self, sq: Square) -> Option<Piece>;
                    fn get_move_history(&self) -> _rt::Vec<MoveHistoryEntry>;
                    fn reset(&self) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_chess_engine_engine_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "chess:engine/engine@0.1.0#[constructor]game")] unsafe extern "C"
                        fn export_constructor_game() -> i32 { unsafe {
                        $($path_to_types)*:: _export_constructor_game_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > () } } #[unsafe (export_name
                        = "chess:engine/engine@0.1.0#[static]game.from-fen")] unsafe
                        extern "C" fn export_static_game_from_fen(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_static_game_from_fen_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Game > (arg0, arg1) } } #[unsafe (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-fen")] unsafe extern
                        "C" fn export_method_game_get_fen(arg0 : * mut u8,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_method_game_get_fen_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Game > (arg0) } } #[unsafe (export_name =
                        "cabi_post_chess:engine/engine@0.1.0#[method]game.get-fen")]
                        unsafe extern "C" fn _post_return_method_game_get_fen(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_game_get_fen::<<$ty as $($path_to_types)*::
                        Guest >::Game > (arg0) } } #[unsafe (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-board-state")] unsafe
                        extern "C" fn export_method_game_get_board_state(arg0 : * mut
                        u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_get_board_state_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_chess:engine/engine@0.1.0#[method]game.get-board-state")]
                        unsafe extern "C" fn
                        _post_return_method_game_get_board_state(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_get_board_state::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-legal-moves")] unsafe
                        extern "C" fn export_method_game_get_legal_moves(arg0 : * mut
                        u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_get_legal_moves_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_chess:engine/engine@0.1.0#[method]game.get-legal-moves")]
                        unsafe extern "C" fn
                        _post_return_method_game_get_legal_moves(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_get_legal_moves::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name =
                        "chess:engine/engine@0.1.0#[method]game.make-move")] unsafe
                        extern "C" fn export_method_game_make_move(arg0 : * mut u8, arg1
                        : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_method_game_make_move_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0, arg1, arg2) } }
                        #[unsafe (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-game-result")] unsafe
                        extern "C" fn export_method_game_get_game_result(arg0 : * mut
                        u8,) -> i32 { unsafe { $($path_to_types)*::
                        _export_method_game_get_game_result_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name =
                        "chess:engine/engine@0.1.0#[method]game.is-check")] unsafe extern
                        "C" fn export_method_game_is_check(arg0 : * mut u8,) -> i32 {
                        unsafe { $($path_to_types)*::
                        _export_method_game_is_check_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Game > (arg0) } } #[unsafe (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-turn")] unsafe extern
                        "C" fn export_method_game_get_turn(arg0 : * mut u8,) -> i32 {
                        unsafe { $($path_to_types)*::
                        _export_method_game_get_turn_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Game > (arg0) } } #[unsafe (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-piece-at")] unsafe
                        extern "C" fn export_method_game_get_piece_at(arg0 : * mut u8,
                        arg1 : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_get_piece_at_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "chess:engine/engine@0.1.0#[method]game.get-move-history")]
                        unsafe extern "C" fn export_method_game_get_move_history(arg0 : *
                        mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_game_get_move_history_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_chess:engine/engine@0.1.0#[method]game.get-move-history")]
                        unsafe extern "C" fn
                        _post_return_method_game_get_move_history(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_game_get_move_history::<<$ty as
                        $($path_to_types)*:: Guest >::Game > (arg0) } } #[unsafe
                        (export_name = "chess:engine/engine@0.1.0#[method]game.reset")]
                        unsafe extern "C" fn export_method_game_reset(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        _export_method_game_reset_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Game > (arg0) } } const _ : () = { #[doc(hidden)]
                        #[unsafe (export_name = "chess:engine/engine@0.1.0#[dtor]game")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: Game::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::Game > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_chess_engine_engine_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 8 + 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8
                        + 5 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_chess_engine_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::chess::engine::engine::__export_chess_engine_engine_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::chess::engine::engine);
    };
}
#[doc(inline)]
pub(crate) use __export_chess_engine_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:chess:engine@0.1.0:chess-engine:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1526] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf3\x0a\x01A\x02\x01\
A\x0c\x01B\x18\x01m\x06\x04pawn\x06knight\x06bishop\x04rook\x05queen\x04king\x04\
\0\x0apiece-type\x03\0\0\x01m\x02\x05white\x05black\x04\0\x05color\x03\0\x02\x01\
r\x02\x0apiece-type\x01\x05color\x03\x04\0\x05piece\x03\0\x04\x01}\x04\0\x06squa\
re\x03\0\x06\x01s\x04\0\x04move\x03\0\x08\x01r\x02\x08uci-move\x09\x0dresulting-\
fens\x04\0\x12move-history-entry\x03\0\x0a\x01r\x04\x0ewhite-kingside\x7f\x0fwhi\
te-queenside\x7f\x0eblack-kingside\x7f\x0fblack-queenside\x7f\x04\0\x08castling\x03\
\0\x0c\x01k\x05\x01p\x0e\x01k\x07\x01p\x0b\x01r\x07\x07squares\x0f\x04turn\x03\x0f\
castling-rights\x0d\x0aen-passant\x10\x0ehalfmove-clock{\x0ffullmove-number{\x0c\
move-history\x11\x04\0\x0bboard-state\x03\0\x12\x01m\x04\x0bin-progress\x09check\
mate\x09stalemate\x04draw\x04\0\x0bgame-result\x03\0\x14\x01m\x03\x0binvalid-fen\
\x0cillegal-move\x09game-over\x04\0\x0cengine-error\x03\0\x16\x03\0\x17chess:typ\
es/types@0.1.0\x05\0\x02\x03\0\0\x0bboard-state\x02\x03\0\0\x04move\x02\x03\0\0\x0b\
game-result\x02\x03\0\0\x05color\x02\x03\0\0\x05piece\x02\x03\0\0\x06square\x02\x03\
\0\0\x0cengine-error\x02\x03\0\0\x12move-history-entry\x01B0\x02\x03\x02\x01\x01\
\x04\0\x0bboard-state\x03\0\0\x02\x03\x02\x01\x02\x04\0\x04move\x03\0\x02\x02\x03\
\x02\x01\x03\x04\0\x0bgame-result\x03\0\x04\x02\x03\x02\x01\x04\x04\0\x05color\x03\
\0\x06\x02\x03\x02\x01\x05\x04\0\x05piece\x03\0\x08\x02\x03\x02\x01\x06\x04\0\x06\
square\x03\0\x0a\x02\x03\x02\x01\x07\x04\0\x0cengine-error\x03\0\x0c\x02\x03\x02\
\x01\x08\x04\0\x12move-history-entry\x03\0\x0e\x04\0\x04game\x03\x01\x01i\x10\x01\
@\0\0\x11\x04\0\x11[constructor]game\x01\x12\x01j\x01\x11\x01\x0d\x01@\x01\x03fe\
ns\0\x13\x04\0\x15[static]game.from-fen\x01\x14\x01h\x10\x01@\x01\x04self\x15\0s\
\x04\0\x14[method]game.get-fen\x01\x16\x01@\x01\x04self\x15\0\x01\x04\0\x1c[meth\
od]game.get-board-state\x01\x17\x01p\x03\x01@\x01\x04self\x15\0\x18\x04\0\x1c[me\
thod]game.get-legal-moves\x01\x19\x01j\0\x01\x0d\x01@\x02\x04self\x15\x03uci\x03\
\0\x1a\x04\0\x16[method]game.make-move\x01\x1b\x01@\x01\x04self\x15\0\x05\x04\0\x1c\
[method]game.get-game-result\x01\x1c\x01@\x01\x04self\x15\0\x7f\x04\0\x15[method\
]game.is-check\x01\x1d\x01@\x01\x04self\x15\0\x07\x04\0\x15[method]game.get-turn\
\x01\x1e\x01k\x09\x01@\x02\x04self\x15\x02sq\x0b\0\x1f\x04\0\x19[method]game.get\
-piece-at\x01\x20\x01p\x0f\x01@\x01\x04self\x15\0!\x04\0\x1d[method]game.get-mov\
e-history\x01\"\x01@\x01\x04self\x15\x01\0\x04\0\x12[method]game.reset\x01#\x04\0\
\x19chess:engine/engine@0.1.0\x05\x09\x04\0\x1fchess:engine/chess-engine@0.1.0\x04\
\0\x0b\x12\x01\0\x0cchess-engine\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
